/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 crystal_golem_heart.glb --transform
Author: Artsem Kalitsenya (https://sketchfab.com/DonKalishman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crystal-golem-heart-53d0e4d69acc413e99d27680cddd11ac
Title: Crystal Golem Heart
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function CrystalHeart(props) {
  const ref = useRef()
  const { nodes, materials } = useGLTF('/Assets/crystal_golem_heart_draco.glb')
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.set(0, t/2, 0) 
  })
  return (
    <group {...props} dispose={null}>
      <group ref={ref}>
        <mesh geometry={nodes['Hart_02_-_Default_0'].geometry} material={materials['02_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/crystal_golem_heart_draco.glb')
