/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 round_platform.glb --transform
Author: noortjeschuur (https://sketchfab.com/noortjeschuur)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/round-platform-64de8f896e3e40e4a1e8a67d01620ac1
Title: round platform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RoundPlatform(props) {
  const { nodes, materials } = useGLTF('/Assets/round_platform-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder1_defaultPolygonShader1_0.geometry} material={materials.defaultPolygonShader1} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/round_platform-transformed.glb')
